[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
